#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 17 10:09:28 2018

@author: gil_privat
"""

# Importing required libraries
import numpy as np

# Defining the variables
total_cost = float(input('Enter the total costs of your desired house: '))
portion_down_payment = total_cost * 0.25
print('Your down payment has to be ', portion_down_payment)
current_savings = float(input('Your current savings are: '))
monthly_salary = float(input('Your monthly salary is: '))
r = 0.04
print('You save at an interest rate of ', r*100, '%')
savings_rate = float(input('Your monthly savings rate is: '))
months = 0

# Computing the number of months required for the down payment
while current_savings < portion_down_payment:
    current_savings = current_savings * (1+r/12) + savings_rate*monthly_salary
    months = months + 1

print('You need to save for at least ',months/12, ' years')




