#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 17 12:02:44 2018

@author: gil_privat
"""

# Importing required libraries
import numpy as np

# Defining the variables
total_cost = float(input('Enter the total costs of your desired house: '))
portion_down_payment = total_cost * 0.25
print('Your down payment has to be ', portion_down_payment)
current_savings = float(input('Your current savings are: '))
monthly_salary = float(input('Your monthly salary is: '))
r = 0.04
print('You save at an interest rate of ', r*100, '%')
savings_rate = float(input('Your monthly savings rate is: '))
months = 0
salary_increase = float(input('Your semi-annually salary growth is: '))

# Computing the number of months required for the down payment
while current_savings < portion_down_payment:
    months = months + 1
    remainder = months % 6
    if remainder == 0:
        monthly_salary = monthly_salary + salary_increase * monthly_salary
    else:
        monthly_salary = monthly_salary
    current_savings = current_savings * (1+r/12) + savings_rate*monthly_salary
    

print('You need to save for at least ',months, ' months')