#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 15 18:46:57 2018

@author: gil_privat
"""
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


x = int(input('Enter a number x: '))
y = int(input('Enter a number y: '))
print('x^y = ',x**y)
print('log_2(x) = ',np.log2(x)) 